### ISSUE TITLE
Add text from RIR proposal to the website

### ISSUE THREAD

**Issue by Chris-Evelo** [bridgedb/website#10]
We wrote down quite some good ideas about BridgeDb governance, work methods, QC, and future developments in the RIR rebuttal document and then removed them. They are saved here: https://docs.google.com/document/d/1oYz9_TmAeOehBES3YLqWGAXyPcFvBGj7JBSYVblQV3Y/edit 

Can you check how to best integrate this in the website?

**Comment by DeniseSl22** [comment]
@Chris-Evelo I don't have edit rights to this document, just send the owner of the email a request for that (so I can add notes in the document what is integrated yes/no(and why not)).

**Comment by Chris-Evelo** [comment]
OK, I just changed the sharing settings to anyone with the link can edit
