### ISSUE TITLE
Camel case

### ISSUE THREAD

**Issue by Chris-Evelo** [bridgedb/website#12]
There are quite some cases where all-caps is used.

**Comment by DeniseSl22** [comment]
@Chris-Evelo I don't see where, and do you mean for BridgeDb, or also at other places?
Please add the specific pages you mean, so I know where to look.

**Comment by Chris-Evelo** [comment]
Yes, that was about BridgeDb. But I think Nuno already fixed that. There are all caps appearances in the ELIXIR RIR announcement but that is the only thing I see now.

**Comment by DeniseSl22** [comment]
Ah okay; yes the Elixir announcement is a header (so the whole text is in caps). If I need to change that, I need to go into the CSS file behind the HTML layout; so that's a bit (or a lot) more work.

**Comment by Chris-Evelo** [comment]
Not worth it
