### ISSUE TITLE
bridgedb.org not loading

### ISSUE THREAD

**Issue by AlasdairGray** [bridgedb/website#16]
I'm getting DNS failures when trying to resolve any bridgedb.org URL.

**Comment by nunogit** [comment]
I just checked the domain name servers (DNS) for BridgeDb:

NS51.DOMAINCONTROL.COM
NS52.DOMAINCONTROL.COM

As far as I can tell they are both working. 
It doesn't mean that they (servers) or the network connection aren't falling erratically.
I tested from both the UM network (VPN) and my (home) network.

@AlasdairGray  is it possible that that can be a problem/failure with either your local DNS or network?

@egonw @mkutmon did you also experience these failures?

**Comment by AlasdairGray** [comment]
It may be an issue on our side. Since I logged the ticket the HWU network keeps dropping out. I think we are having another DDoS attack.

**Comment by egonw** [comment]
@AlasdairGray, got an update?

**Comment by AlasdairGray** [comment]
I believe that this is a HWU issue. I can access the page using other networks.
