### ISSUE TITLE
write up a "resource commitment"

### ISSUE THREAD

**Issue by egonw** [bridgedb/website#2]

**Comment by DeniseSl22** [comment]
What do you mean with this statement? Please specify @egonw

**Comment by egonw** [comment]
Ah, right... in overview of past, current, and future funding, possibly in kind.

**Comment by DeniseSl22** [comment]
Ah okay, that sounds more specific ;) Can I use the Elixir proposal text for this part? I think Chris made a nice summary in here.... I can add the information then to the "collaborators" part of the website? I do not necessarily want to make more pages, but it is good to get more content on the current ones.

**Comment by egonw** [comment]
Yes, let's use that text then as a first version. I don't remember what it said... but what's important is that we list funding that contributed/-es to it.

**Comment by DeniseSl22** [comment]
I added it, see https://www.bridgedb.org/development/ .
