### ISSUE TITLE
BridgeDb gene database annotations

### ISSUE THREAD

**Issue by Chris-Evelo** [bridgedb/website#4]
The BridgeDb gene databases on https://www.bridgedb.org/mapping-databases/ensembl-gene-mappings/ should also have common names for species. 

For other species it links out to the FTP site but I don't see anything there to figure out which species we actually have or what is in which database

**Comment by DeniseSl22** [comment]
Okay, I think Jonathan fixed this in the meantime, we now have a Table providing more structured info on the diff. species:
![image](https://user-images.githubusercontent.com/26277832/49014176-850a8580-f17f-11e8-8aab-389128b65822.png)

Is this what you had in mind @Chris-Evelo ? If not, let me know what needs to change!

**Comment by Chris-Evelo** [comment]
Yes, except I would have a look at the taxon ontology and also provide the English versions of the species names. Mainly to make sure these show up in searches (human, rat, mouse etc), should be in line with the species descriptions we have for the pathways

**Comment by DeniseSl22** [comment]
I think this will be handled with the new folder system @nunogit is setting up, so the data is stored with (more) structure. I've now added the common names and the System codes to the table.
