### ISSUE TITLE
Revisit website pages and clean up text

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/website#5]
Since we changed the layout, it would also be nice to read all pages again and make them more clear for users. I've did my fair share, but if anyone has some detailed knowledge on certain implementations, please add that information as detailed as you can, and check the box of the page below (and write your name behind the item, so I know who checked what):

- [ ] HOME

- [ ] Documentation
- [ ] How to cite
- [ ] Framework
- [ ] System Codes

- [ ] Webservice
- [ ] Webservice Implementation

- [ ] Download

- [ ] Identifier Mapping Databases
- [ ] Ensembl Gene and Protein Mappings
- [ ]  Gene-Variant Mappings 
- [ ] Metabolite ID Mappings 
- [ ] Rhea Interaction Mappings

- [ ] Development

**Comment by egonw** [comment]
I'll close this one. If people have comments, please open an Issue or make a Pull Request in this repo:  https://github.com/bridgedb/bridgedb.github.io
